server:
  servlet:
    context-path: /api

spring:
  application:
    name: monolith-to-microservices

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
